name = fsfcraftguide
description = An augmented experimental mtg_craftguide. Supports a progressive reveal system that follows docs item help.
depends = flow, flow_extras
optional_depends = doc, doc_items, sway, flinv, sfinv, mtg_craftguide, sfcraftguide
min_minetest_version = 5.0
supported_games = minetest_game, whynot
